language: cpp
sudo: required
dist: trusty

os:
    - linux
    - osx

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-format-3.8
      - build-essential
      - automake
      - libtool
      - ccache
      - cmake

script:
    - mkdir build && cd build
    - cmake ..
    - make

notifications:
  email:
    on_success: change
    on_failure: always
